# Generated by Django 2.2 on 2021-02-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20210209_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeeditem',
            name='is_on',
            field=models.BooleanField(default=True),
        ),
    ]
