# Generated by Django 2.2 on 2021-02-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_profilefeeditem_is_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='is_on',
        ),
    ]
